version: '3'

services:
    api:
        build:
            context: ./
            dockerfile: docker/api/Dockerfile
        env_file:
          - ./.env
        ports:
          - "9000:8000"
        volumes:
          - "./src/:/app/src/"
