version: '3'

services:
    api:
        build:
            context: ./
            dockerfile: docker/api/Dockerfile
        env_file:
          - ./.env
        ports:
          - "${GUNICORN_PORT}:${GUNICORN_PORT}"
        volumes:
          - "./src/:/app/src/"
